import { buildSupportTraceJourney, listAllSupportTraceJourneys, listFailedSupportTraceJourneys, listReserveSupportTraceJourneys, type SupportTraceJourney } from "./support_trace_index.js";
export interface SupportTraceReport { readonly requestId:string; readonly rootRequestId:string; readonly parentRequestId?:string; readonly headline:string; readonly responderId?:string; readonly matchedCapability?:string; readonly accepted:boolean; readonly reserveUsed:boolean; readonly followUpNeeded:boolean; readonly failed:boolean; readonly warningCount:number; readonly startedAt?:string; readonly completedAt?:string; readonly stoppedBecause?:string; readonly summaryLines:readonly string[]; }
export interface SupportTraceOverviewReport { readonly totalJourneys:number; readonly failedJourneys:number; readonly reserveJourneys:number; readonly summaryLines:readonly string[]; }
const head=(j:SupportTraceJourney)=>j.failed?"Support request encountered execution failure.":j.reserveUsed?"Support request completed with reserve participation.":j.followUpNeeded?"Support request completed and requested bounded follow-up.":j.accepted?"Support request completed without major escalation.":"Support request did not reach a successful execution state.";
const lines=(j:SupportTraceJourney)=>[`request id: ${j.requestId}`,`root request id: ${j.rootRequestId}`,`parent request id: ${j.parentRequestId ?? '(none / root request)'}`,`accepted: ${j.accepted?'yes':'no'}`,`reserve used: ${j.reserveUsed?'yes':'no'}`,`follow-up needed: ${j.followUpNeeded?'yes':'no'}`,`failed: ${j.failed?'yes':'no'}`,`warning count: ${j.warningCount}`,...(j.responderId?[`responder id: ${j.responderId}`]:[]),...(j.matchedCapability?[`matched capability: ${j.matchedCapability}`]:[]),...(j.startedAt?[`started at: ${j.startedAt}`]:[]),...(j.completedAt?[`completed at: ${j.completedAt}`]:[]),...(j.stoppedBecause?[`latest stage: ${j.stoppedBecause}`]:[]),`trace entry count: ${j.entries.length}`];
export const buildSupportTraceReport=(j:SupportTraceJourney):SupportTraceReport=>({requestId:j.requestId,rootRequestId:j.rootRequestId,parentRequestId:j.parentRequestId,headline:head(j),responderId:j.responderId,matchedCapability:j.matchedCapability,accepted:j.accepted,reserveUsed:j.reserveUsed,followUpNeeded:j.followUpNeeded,failed:j.failed,warningCount:j.warningCount,startedAt:j.startedAt,completedAt:j.completedAt,stoppedBecause:j.stoppedBecause,summaryLines:lines(j)});
export const buildSupportTraceReportByRequestId=(requestId:string):SupportTraceReport=>buildSupportTraceReport(buildSupportTraceJourney(requestId));
export const buildAllSupportTraceReports=():readonly SupportTraceReport[]=>listAllSupportTraceJourneys().map(buildSupportTraceReport);
export const buildSupportTraceOverviewReport=():SupportTraceOverviewReport=>({ totalJourneys:listAllSupportTraceJourneys().length, failedJourneys:listFailedSupportTraceJourneys().length, reserveJourneys:listReserveSupportTraceJourneys().length, summaryLines:[`total journeys: ${listAllSupportTraceJourneys().length}`,`failed journeys: ${listFailedSupportTraceJourneys().length}`,`reserve journeys: ${listReserveSupportTraceJourneys().length}`] });
