import type { SupportTraceLineageOverviewReport, SupportTraceLineageReport, SupportTraceLineageReportRequestNode } from "./support_trace_lineage_report.js";
import { buildAllSupportTraceLineageReports, buildSupportTraceLineageOverviewReport, buildSupportTraceLineageReportByRootRequestId } from "./support_trace_lineage_report.js";
const yn=(v:boolean)=>v?'yes':'no';
const node=(n:SupportTraceLineageReportRequestNode)=>[`#### ${n.requestId}`,"",`- Root request: **${n.rootRequestId}**`,`- Parent request: **${n.parentRequestId ?? '(none / root request)'}**`,`- Failed: **${yn(n.failed)}**`,`- Reserve used: **${yn(n.reserveUsed)}**`,...(n.stoppedBecause?[`- Stopped because: **${n.stoppedBecause}**`]:[]),""];
export function renderSupportTraceLineageOverviewMarkdown(o:SupportTraceLineageOverviewReport):string{ const L=["# Support Trace Lineage Overview","",`- Total lineages: **${o.totalLineages}**`,`- Failed lineages: **${o.failedLineages}**`,`- Reserve lineages: **${o.reserveLineages}**`,""]; if(o.summaryLines.length){L.push("## Overview Summary",""); for(const s of o.summaryLines)L.push(`- ${s}`); L.push("");} return L.join("\n"); }
export function renderSupportTraceLineageReportMarkdown(r:SupportTraceLineageReport):string{ const L=[`## Root Request ${r.rootRequestId}`,"",`**Headline:** ${r.headline}`,"",`- Request count: **${r.requestCount}**`,`- Follow-up count: **${r.followUpCount}**`,`- Reserve used: **${yn(r.reserveUsed)}**`,`- Failed: **${yn(r.failed)}**`,...(r.stoppedReasons.length?[`- Stopped reasons: **${r.stoppedReasons.join(', ')}**`]:[]),""]; if(r.requestIds.length){L.push("### Request IDs",""); for(const id of r.requestIds)L.push(`- ${id}`); L.push("");} if(r.requestNodes.length){L.push("### Request Nodes",""); for(const n of r.requestNodes)L.push(...node(n));} if(r.summaryLines.length){L.push("### Summary",""); for(const s of r.summaryLines)L.push(`- ${s}`); L.push("");} return L.join("\n"); }
export function renderSupportTraceLineageDocumentMarkdown(reports:readonly SupportTraceLineageReport[], overview?:SupportTraceLineageOverviewReport):string{ const L=["# Support Trace Lineage Report",""]; if(overview){L.push(renderSupportTraceLineageOverviewMarkdown(overview),"");} if(!reports.length){L.push("_No support trace lineage reports available._",""); return L.join("\n");} L.push("## Lineages",""); for(const r of reports)L.push(renderSupportTraceLineageReportMarkdown(r)); return L.join("\n"); }
export const renderSupportTraceLineageMarkdownByRootRequestId=(rootRequestId:string):string=>renderSupportTraceLineageReportMarkdown(buildSupportTraceLineageReportByRootRequestId(rootRequestId));
export const renderAllSupportTraceLineageMarkdown=():string=>renderSupportTraceLineageDocumentMarkdown(buildAllSupportTraceLineageReports(), buildSupportTraceLineageOverviewReport());
