import { buildSupportTraceLineage, listAllSupportTraceLineages, listFailedSupportTraceLineages, listReserveSupportTraceLineages, type SupportTraceLineage, type SupportTraceLineageRequestNode } from "./support_trace_lineage.js";
export interface SupportTraceLineageReportRequestNode { readonly requestId:string; readonly rootRequestId:string; readonly parentRequestId?:string; readonly failed:boolean; readonly reserveUsed:boolean; readonly stoppedBecause?:string; }
export interface SupportTraceLineageReport { readonly rootRequestId:string; readonly headline:string; readonly requestCount:number; readonly followUpCount:number; readonly reserveUsed:boolean; readonly failed:boolean; readonly stoppedReasons:readonly string[]; readonly requestIds:readonly string[]; readonly requestNodes:readonly SupportTraceLineageReportRequestNode[]; readonly summaryLines:readonly string[]; }
export interface SupportTraceLineageOverviewReport { readonly totalLineages:number; readonly failedLineages:number; readonly reserveLineages:number; readonly summaryLines:readonly string[]; }
const head=(l:SupportTraceLineage)=>l.failed?"Support lineage contains failure signals.":l.reserveUsed?"Support lineage completed with reserve participation.":l.followUpCount>0?"Support lineage involved follow-up continuity.":"Support lineage completed without major escalation.";
const node=(n:SupportTraceLineageRequestNode):SupportTraceLineageReportRequestNode=>({requestId:n.requestId,rootRequestId:n.rootRequestId,parentRequestId:n.parentRequestId,failed:n.journey.failed,reserveUsed:n.journey.reserveUsed,stoppedBecause:n.journey.stoppedBecause});
const lines=(l:SupportTraceLineage)=>[`root request id: ${l.rootRequestId}`,`request count: ${l.requestIds.length}`,`follow-up count: ${l.followUpCount}`,`reserve used: ${l.reserveUsed?'yes':'no'}`,`failed: ${l.failed?'yes':'no'}`,...(l.stoppedReasons.length?[`stopped reasons: ${l.stoppedReasons.join(', ')}`]:[]),...(l.requestIds.length?[`request ids: ${l.requestIds.join(' | ')}`]:[]),`root node present: ${l.requestNodes.find(n=>n.requestId===l.rootRequestId)?'yes':'no'}`,`parent-linked requests: ${l.requestNodes.filter(n=>typeof n.parentRequestId==='string').length}`,`latest lineage request stopped because: ${l.journeys.at(-1)?.stoppedBecause ?? 'unknown'}`];
export const buildSupportTraceLineageReport=(l:SupportTraceLineage):SupportTraceLineageReport=>({rootRequestId:l.rootRequestId,headline:head(l),requestCount:l.requestIds.length,followUpCount:l.followUpCount,reserveUsed:l.reserveUsed,failed:l.failed,stoppedReasons:l.stoppedReasons,requestIds:l.requestIds,requestNodes:l.requestNodes.map(node),summaryLines:lines(l)});
export const buildSupportTraceLineageReportByRootRequestId=(rootRequestId:string):SupportTraceLineageReport=>buildSupportTraceLineageReport(buildSupportTraceLineage(rootRequestId));
export const buildAllSupportTraceLineageReports=():readonly SupportTraceLineageReport[]=>listAllSupportTraceLineages().map(buildSupportTraceLineageReport);
export const buildSupportTraceLineageOverviewReport=():SupportTraceLineageOverviewReport=>({ totalLineages:listAllSupportTraceLineages().length, failedLineages:listFailedSupportTraceLineages().length, reserveLineages:listReserveSupportTraceLineages().length, summaryLines:[`total lineages: ${listAllSupportTraceLineages().length}`,`failed lineages: ${listFailedSupportTraceLineages().length}`,`reserve lineages: ${listReserveSupportTraceLineages().length}`] });
