import type { SupportRequest } from "./support/core/support_interface.js";
import { clearSupportTraceStore, listSupportTraceEntries } from "./support/trace/support_trace.js";
import { clearSupportEngineTraceStore, listSupportEngineTraceEntries } from "./support/trace/support_engine_trace.js";
import { runSupportReportRuntime } from "./support/runtime/support_report_runtime.js";
function createValidationRequest(): SupportRequest { const requestId = "req-validation-001"; return { requestId, rootRequestId: requestId, requesterId: "system", requestType: "validation", urgency: "degraded", automatic: false, allowReserve: false, reason: "Structural uncertainty remains visible after recent degradation.", contextNotes: "Validation should expose unresolved weak points without overstating recovery." }; }
function createRepairRequest(): SupportRequest { const requestId = "req-repair-001"; return { requestId, rootRequestId: requestId, requesterId: "system", requestType: "repair", urgency: "degraded", automatic: false, allowReserve: false, reason: "Known repair debt should be handled conservatively.", contextNotes: "Repair should stay bounded and avoid broad restructuring." }; }
function createReentryRequest(): SupportRequest { const requestId = "req-reentry-001"; return { requestId, rootRequestId: requestId, requesterId: "system", requestType: "reentry", urgency: "normal", automatic: true, allowReserve: false, reason: "A guarded return to the active path is needed.", contextNotes: "Reentry should remain narrow and supervised until later validation or repair confirms stability." }; }
function printDivider(title: string): void { console.log("\n" + "=".repeat(72)); console.log(title); console.log("=".repeat(72)); }
function resetTraceStores(): void { clearSupportTraceStore(); clearSupportEngineTraceStore(); }
function printTraceCounts(): void { console.log("[Trace Counts]"); console.log("runtimeTraceCount:", listSupportTraceEntries().length); console.log("engineTraceCount:", listSupportEngineTraceEntries().length); }
function runPresetScenario(title: string, request: SupportRequest, presetName: "minimal" | "review" | "archive" | "full_compare"): void {
  printDivider(`${title} (${presetName})`);
  const result = runSupportReportRuntime(request, { presetName, engineOptions: { maxSteps: 2 } });
  console.log("[Preset]"); console.log("name:", result.preset.name); console.log("message:", result.message); console.log("warnings:", result.warnings);
  if (result.runtimeResult) { console.log("[Runtime Result]"); console.log("executed:", result.runtimeResult.executed); console.log("selectedNodeId:", result.runtimeResult.selectedNodeId ?? "none"); console.log("matchedCapability:", result.runtimeResult.matchedCapability ?? "none"); console.log("responderId:", result.runtimeResult.response.responderId); console.log("accepted:", result.runtimeResult.response.accepted); console.log("followUpNeeded:", result.runtimeResult.response.followUpNeeded === true); console.log("actionSummary:", result.runtimeResult.response.actionSummary); }
  if (result.engineResult) { console.log("[Engine Result]"); console.log("ok:", result.engineResult.ok); console.log("stepCount:", result.engineResult.steps.length); console.log("stoppedBecause:", result.engineResult.stoppedBecause); console.log("finalResponderId:", result.engineResult.finalResponse.responderId); console.log("finalAccepted:", result.engineResult.finalResponse.accepted); console.log("finalFollowUpNeeded:", result.engineResult.finalResponse.followUpNeeded === true); }
  if (result.traceMarkdown) { console.log("[Trace Markdown Preview]"); console.log(result.traceMarkdown.slice(0, 800)); }
  if (result.lineageMarkdown) { console.log("[Lineage Markdown Preview]"); console.log(result.lineageMarkdown.slice(0, 800)); }
  if (result.archiveResult) { console.log("[Archive Result]"); console.log("ok:", result.archiveResult.ok); console.log("timestamp:", result.archiveResult.timestamp); console.log("archiveFolder:", result.archiveResult.archiveFolder); console.log("bundleJson:", result.archiveResult.bundleJsonWrite.filePath); console.log("bundleMarkdown:", result.archiveResult.bundleMarkdownWrite.filePath); }
  if (result.diffResult) { console.log("[Diff Result]"); console.log("ok:", result.diffResult.ok); console.log("beforeTimestamp:", result.diffResult.beforeTimestamp ?? "none"); console.log("afterTimestamp:", result.diffResult.afterTimestamp ?? "none"); console.log("message:", result.diffResult.message); if (result.diffResult.diffReport) { console.log("diffHeadline:", result.diffResult.diffReport.headline); console.log("runtimeDelta:", result.diffResult.diffReport.runtimeTraceCountDelta); console.log("engineDelta:", result.diffResult.diffReport.engineTraceCountDelta); } }
  printTraceCounts();
}
function main(): void { resetTraceStores(); runPresetScenario("SCENARIO 1: VALIDATION", createValidationRequest(), "minimal"); runPresetScenario("SCENARIO 2: REPAIR", createRepairRequest(), "review"); runPresetScenario("SCENARIO 3: REENTRY", createReentryRequest(), "archive"); runPresetScenario("SCENARIO 4: REENTRY FULL COMPARE", createReentryRequest(), "full_compare"); }
main();
